// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-releaser-agent/pkg/githubtags"
)

type TagsFetcher struct {
	LatestSemverTagStub        func(context.Context, string, string) (string, error)
	latestSemverTagMutex       sync.RWMutex
	latestSemverTagArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	latestSemverTagReturns struct {
		result1 string
		result2 error
	}
	latestSemverTagReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TagsFetcher) LatestSemverTag(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.latestSemverTagMutex.Lock()
	ret, specificReturn := fake.latestSemverTagReturnsOnCall[len(fake.latestSemverTagArgsForCall)]
	fake.latestSemverTagArgsForCall = append(fake.latestSemverTagArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.LatestSemverTagStub
	fakeReturns := fake.latestSemverTagReturns
	fake.recordInvocation("LatestSemverTag", []interface{}{arg1, arg2, arg3})
	fake.latestSemverTagMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TagsFetcher) LatestSemverTagCallCount() int {
	fake.latestSemverTagMutex.RLock()
	defer fake.latestSemverTagMutex.RUnlock()
	return len(fake.latestSemverTagArgsForCall)
}

func (fake *TagsFetcher) LatestSemverTagCalls(stub func(context.Context, string, string) (string, error)) {
	fake.latestSemverTagMutex.Lock()
	defer fake.latestSemverTagMutex.Unlock()
	fake.LatestSemverTagStub = stub
}

func (fake *TagsFetcher) LatestSemverTagArgsForCall(i int) (context.Context, string, string) {
	fake.latestSemverTagMutex.RLock()
	defer fake.latestSemverTagMutex.RUnlock()
	argsForCall := fake.latestSemverTagArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TagsFetcher) LatestSemverTagReturns(result1 string, result2 error) {
	fake.latestSemverTagMutex.Lock()
	defer fake.latestSemverTagMutex.Unlock()
	fake.LatestSemverTagStub = nil
	fake.latestSemverTagReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *TagsFetcher) LatestSemverTagReturnsOnCall(i int, result1 string, result2 error) {
	fake.latestSemverTagMutex.Lock()
	defer fake.latestSemverTagMutex.Unlock()
	fake.LatestSemverTagStub = nil
	if fake.latestSemverTagReturnsOnCall == nil {
		fake.latestSemverTagReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.latestSemverTagReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *TagsFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TagsFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ githubtags.TagsFetcher = new(TagsFetcher)
